FROM python:3

WORKDIR /app

COPY allsnps/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y tabix && rm -rf /var/lib/apt/lists/*

COPY app.config ./
COPY allSNPs.py ./