FROM python:2

# Set default work directory
WORKDIR /app

COPY gwas_file/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app.config ./
COPY gwas_file.py ./


# Configure non-root user.
ARG USERNAME
ARG PUID
ARG PGID

RUN groupadd --gid ${PGID} $USERNAME && \
    useradd -l --non-unique --uid ${PUID} --gid ${PGID} $USERNAME

USER $USERNAME