FROM python:2

WORKDIR /app

COPY magma/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends curl unzip build-essential r-base \
    && curl https://ctg.cncr.nl/software/MAGMA/prog/magma_v1.10_static.zip -o magma_v1.10_static.zip\
    && unzip magma_v1.10_static.zip -d /usr/local/share/MAGMA \
    && rm magma_v1.10_static.zip \
    && rm -rf /var/lib/apt/lists/*
    

RUN Rscript -e "install.packages('data.table')"
RUN Rscript -e "install.packages('kimisc')"

COPY app.config ./
COPY magma.py ./
COPY magma_gene.R ./
COPY ConfigParser.R ./