FROM r-base:4.2.3

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN Rscript -e "install.packages(c('rprojroot', 'whereami', 'data.table', 'kimisc', 'BiocManager'))"
RUN Rscript -e "BiocManager::install('GenomicRanges')"

COPY app.config ./
COPY ConfigParser.R ./
COPY geneMap.R ./