FROM python:3

WORKDIR /app

COPY get_gwas_catalog/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app.config ./
COPY getGWAScatalog.py ./

# Configure non-root user.
ARG USERNAME
ARG PUID
ARG PGID

RUN groupadd --gid ${PGID} $USERNAME && \
    useradd -l --non-unique --uid ${PUID} --gid ${PGID} $USERNAME

USER $USERNAME