FROM python:2

# Set default work directory
WORKDIR /app

COPY g2f/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends build-essential r-base \
    && rm -rf /var/lib/apt/lists/*

RUN Rscript -e "install.packages(c('rprojroot', 'whereami', 'data.table', 'kimisc'))"

COPY app.config ./
COPY g2f_DEGPlot.py ./
COPY g2f_expPlot.py ./
COPY GeneSet.py ./

COPY ConfigParser.R ./
COPY gene2func.R ./

# Configure non-root user.
ARG USERNAME
ARG PUID
ARG PGID

RUN groupadd --gid ${PGID} $USERNAME && \
    useradd -l --non-unique --uid ${PUID} --gid ${PGID} $USERNAME

USER $USERNAME