FROM python:3

WORKDIR /app

COPY allsnps/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y tabix && rm -rf /var/lib/apt/lists/*

COPY app.config ./
COPY allSNPs.py ./

# Configure non-root user.
ARG USERNAME
ARG PUID
ARG PGID

RUN groupadd --gid ${PGID} $USERNAME && \
    useradd -l --non-unique --uid ${PUID} --gid ${PGID} $USERNAME

USER $USERNAME