FROM python:2

WORKDIR /app

COPY getld/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

ARG ANNOVAR_DOWNLOAD_LINK

RUN apt-get update && apt-get install -y --no-install-recommends gzip curl \
    && curl ${ANNOVAR_DOWNLOAD_LINK} -o annovar.latest.tar.gz \
    && tar -xf annovar.latest.tar.gz -C /usr/local/share \
    && rm annovar.latest.tar.gz \
    && rm -rf /var/lib/apt/lists/*

COPY app.config ./
COPY getLD.py ./
COPY annovar.py ./
COPY annov_geneSNPs.pl ./
COPY getTopSNPs.py ./

# Configure non-root user.
ARG USERNAME
ARG PUID
ARG PGID

RUN groupadd --gid ${PGID} $USERNAME && \
    useradd -l --non-unique --uid ${PUID} --gid ${PGID} $USERNAME

USER $USERNAME